// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qodpofxiroiomosaafax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZHBvZnhpcm9pb21vc2FhZmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDE4NzUsImV4cCI6MjA3MDE3Nzg3NX0.GrgWq1C9LXz0kjO0Bc-24s0AR5nQkBWGcFISROsNPIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});